
from synet.utils.common import PathReq
from synet.utils.common import ECMPPathsReq
from synet.utils.common import PathOrderReq
from synet.utils.common import Protocols
from synet.utils.common import KConnectedPathsReq

topology_file = 'topos/small/Bics.graphml'
seed = 2692189509
reqs_simple_1 = [
    PathReq(Protocols.OSPF, "Lisbon", ['Bucharest', 'Kiev', 'Warsaw', 'Frankfurt', 'Amsterdam', 'London', 'Lisbon'], False),
]

edges_cost_simple_1 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 1),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 2),
    ("Frankfurt", "Strasbourg", 1),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 1),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

####################

reqs_ecmp_1_2 = [
    ECMPPathsReq(Protocols.OSPF, 'Bratislava', [PathReq(Protocols.OSPF, "Bratislava", ['Paris', 'Brussels', 'Frankfurt', 'Vienna', 'Bratislava'], False), PathReq(Protocols.OSPF, "Bratislava", ['Paris', 'Brussels', 'Frankfurt', 'Praha', 'Bratislava'], False)], False),
]

edges_cost_ecmp_1_2 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 1),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 1),
    ("Frankfurt", "Strasbourg", 1),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 1),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

reqs_kconnected_1_2 = [
    KConnectedPathsReq(Protocols.OSPF, 'Bratislava', [PathReq(Protocols.OSPF, "Bratislava", ['Paris', 'Brussels', 'Frankfurt', 'Vienna', 'Bratislava'], False), PathReq(Protocols.OSPF, "Bratislava", ['Paris', 'Brussels', 'Frankfurt', 'Praha', 'Bratislava'], False)], False),
]

edges_cost_kconnected_1_2 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 1),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 1),
    ("Frankfurt", "Strasbourg", 1),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 1),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

reqs_order_1_2 = [
    PathOrderReq(Protocols.OSPF, 'Milan', [PathReq(Protocols.OSPF, "Milan", ['Roma', 'Milan'], False), PathReq(Protocols.OSPF, "Milan", ['Roma', 'Zurich', 'Frankfurt', 'Vienna', 'Milan'], False)], False),
]

edges_cost_order_1_2 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 1),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 1),
    ("Frankfurt", "Strasbourg", 1),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 1),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 4),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

reqs_simple_2 = [
    PathReq(Protocols.OSPF, "Bucharest", ['Luxembourg', 'Brussels', 'Frankfurt', 'Warsaw', 'Kiev', 'Bucharest'], False),
    PathReq(Protocols.OSPF, "Geneva", ['Luxembourg', 'Brussels', 'Paris', 'Geneva'], False),
]

edges_cost_simple_2 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 1),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 2),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 1),
    ("Frankfurt", "Strasbourg", 1),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 1),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

####################

reqs_ecmp_2_2 = [
    ECMPPathsReq(Protocols.OSPF, 'Basel', [PathReq(Protocols.OSPF, "Basel", ['Brussels', 'Paris', 'Geneva', 'Basel'], False), PathReq(Protocols.OSPF, "Basel", ['Brussels', 'Luxembourg', 'Strasbourg', 'Basel'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Sofia', [PathReq(Protocols.OSPF, "Sofia", ['Brussels', 'Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Sofia'], False), PathReq(Protocols.OSPF, "Sofia", ['Brussels', 'Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Sofia'], False)], False),
]

edges_cost_ecmp_2_2 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 1),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 1),
    ("Frankfurt", "Strasbourg", 2),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 1),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

reqs_kconnected_2_2 = [
    KConnectedPathsReq(Protocols.OSPF, 'Basel', [PathReq(Protocols.OSPF, "Basel", ['Brussels', 'Paris', 'Geneva', 'Basel'], False), PathReq(Protocols.OSPF, "Basel", ['Brussels', 'Luxembourg', 'Strasbourg', 'Basel'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Sofia', [PathReq(Protocols.OSPF, "Sofia", ['Brussels', 'Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Sofia'], False), PathReq(Protocols.OSPF, "Sofia", ['Brussels', 'Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Sofia'], False)], False),
]

edges_cost_kconnected_2_2 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 1),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 1),
    ("Frankfurt", "Strasbourg", 2),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 1),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

reqs_order_2_2 = [
    PathOrderReq(Protocols.OSPF, 'Basel', [PathReq(Protocols.OSPF, "Basel", ['Strasbourg', 'Basel'], False), PathReq(Protocols.OSPF, "Basel", ['Strasbourg', 'Luxembourg', 'Brussels', 'Paris', 'Geneva', 'Basel'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Paris', [PathReq(Protocols.OSPF, "Paris", ['Brussels', 'Paris'], False), PathReq(Protocols.OSPF, "Paris", ['Brussels', 'London', 'Paris'], False)], False),
]

edges_cost_order_2_2 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 1),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 3),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 1),
    ("Frankfurt", "Strasbourg", 1),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 1),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

reqs_simple_4 = [
    PathReq(Protocols.OSPF, "Lisbon", ['Sofia', 'Budapest', 'Bratislava', 'Praha', 'Frankfurt', 'Brussels', 'London', 'Lisbon'], False),
    PathReq(Protocols.OSPF, "Milan", ['Sofia', 'Budapest', 'Bratislava', 'Vienna', 'Milan'], False),
    PathReq(Protocols.OSPF, "Amsterdam", ['Sofia', 'Budapest', 'Bratislava', 'Praha', 'Frankfurt', 'Amsterdam'], False),
    PathReq(Protocols.OSPF, "Istanbul", ['Sofia', 'Athens', 'Istanbul'], False),
]

edges_cost_simple_4 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 1),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 2),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 1),
    ("Frankfurt", "Strasbourg", 1),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 1),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 2),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

####################

reqs_ecmp_4_2 = [
    ECMPPathsReq(Protocols.OSPF, 'Rotterdam', [PathReq(Protocols.OSPF, "Rotterdam", ['Vienna', 'Frankfurt', 'Brussels', 'Rotterdam'], False), PathReq(Protocols.OSPF, "Rotterdam", ['Vienna', 'Frankfurt', 'Amsterdam', 'Rotterdam'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Geneva', [PathReq(Protocols.OSPF, "Geneva", ['Vienna', 'Milan', 'Zurich', 'Geneva'], False), PathReq(Protocols.OSPF, "Geneva", ['Vienna', 'Frankfurt', 'Zurich', 'Geneva'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Athens', [PathReq(Protocols.OSPF, "Athens", ['Vienna', 'Bratislava', 'Budapest', 'Bucharest', 'Istanbul', 'Athens'], False), PathReq(Protocols.OSPF, "Athens", ['Vienna', 'Bratislava', 'Budapest', 'Sofia', 'Athens'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Lisbon', [PathReq(Protocols.OSPF, "Lisbon", ['Vienna', 'Frankfurt', 'Brussels', 'London', 'Lisbon'], False), PathReq(Protocols.OSPF, "Lisbon", ['Vienna', 'Frankfurt', 'Amsterdam', 'London', 'Lisbon'], False)], False),
]

edges_cost_ecmp_4_2 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 1),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 2),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 1),
    ("Frankfurt", "Strasbourg", 1),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 1),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

reqs_kconnected_4_2 = [
    KConnectedPathsReq(Protocols.OSPF, 'Rotterdam', [PathReq(Protocols.OSPF, "Rotterdam", ['Vienna', 'Frankfurt', 'Brussels', 'Rotterdam'], False), PathReq(Protocols.OSPF, "Rotterdam", ['Vienna', 'Frankfurt', 'Amsterdam', 'Rotterdam'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Geneva', [PathReq(Protocols.OSPF, "Geneva", ['Vienna', 'Milan', 'Zurich', 'Geneva'], False), PathReq(Protocols.OSPF, "Geneva", ['Vienna', 'Frankfurt', 'Zurich', 'Geneva'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Athens', [PathReq(Protocols.OSPF, "Athens", ['Vienna', 'Bratislava', 'Budapest', 'Bucharest', 'Istanbul', 'Athens'], False), PathReq(Protocols.OSPF, "Athens", ['Vienna', 'Bratislava', 'Budapest', 'Sofia', 'Athens'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Lisbon', [PathReq(Protocols.OSPF, "Lisbon", ['Vienna', 'Frankfurt', 'Brussels', 'London', 'Lisbon'], False), PathReq(Protocols.OSPF, "Lisbon", ['Vienna', 'Frankfurt', 'Amsterdam', 'London', 'Lisbon'], False)], False),
]

edges_cost_kconnected_4_2 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 1),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 1),
    ("Frankfurt", "Strasbourg", 1),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 1),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

reqs_order_4_2 = [
    PathOrderReq(Protocols.OSPF, 'Barcelona', [PathReq(Protocols.OSPF, "Barcelona", ['Marseille', 'Barcelona'], False), PathReq(Protocols.OSPF, "Barcelona", ['Marseille', 'Lyon', 'Paris', 'Madrid', 'Barcelona'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Vienna', [PathReq(Protocols.OSPF, "Vienna", ['Milan', 'Vienna'], False), PathReq(Protocols.OSPF, "Vienna", ['Milan', 'Zurich', 'Frankfurt', 'Vienna'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Luxembourg', [PathReq(Protocols.OSPF, "Luxembourg", ['Strasbourg', 'Luxembourg'], False), PathReq(Protocols.OSPF, "Luxembourg", ['Strasbourg', 'Frankfurt', 'Brussels', 'Luxembourg'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Milan', [PathReq(Protocols.OSPF, "Milan", ['Marseille', 'Milan'], False), PathReq(Protocols.OSPF, "Milan", ['Marseille', 'Lyon', 'Geneva', 'Zurich', 'Milan'], False)], False),
]

edges_cost_order_4_2 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 1),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 1),
    ("Frankfurt", "Strasbourg", 1),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 1),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

reqs_simple_8 = [
    PathReq(Protocols.OSPF, "Madrid", ['Kiev', 'Warsaw', 'Frankfurt', 'Brussels', 'Paris', 'Madrid'], False),
    PathReq(Protocols.OSPF, "Geneva", ['Kiev', 'Warsaw', 'Frankfurt', 'Brussels', 'Paris', 'Geneva'], False),
    PathReq(Protocols.OSPF, "Basel", ['Kiev', 'Warsaw', 'Frankfurt', 'Strasbourg', 'Basel'], False),
    PathReq(Protocols.OSPF, "Zagreb", ['Kiev', 'Bucharest', 'Budapest', 'Zagreb'], False),
    PathReq(Protocols.OSPF, "Ljubjana", ['Kiev', 'Bucharest', 'Budapest', 'Zagreb', 'Ljubjana'], False),
    PathReq(Protocols.OSPF, "Rotterdam", ['Kiev', 'Warsaw', 'Frankfurt', 'Brussels', 'Rotterdam'], False),
    PathReq(Protocols.OSPF, "Frankfurt", ['Kiev', 'Warsaw', 'Frankfurt'], False),
    PathReq(Protocols.OSPF, "Lisbon", ['Kiev', 'Warsaw', 'Frankfurt', 'Amsterdam', 'London', 'Lisbon'], False),
]

edges_cost_simple_8 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 1),
    ("Basel", "Geneva", 2),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 2),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 1),
    ("Frankfurt", "Strasbourg", 1),
    ("Frankfurt", "Zurich", 3),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 1),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 2),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

####################

reqs_ecmp_8_2 = [
    ECMPPathsReq(Protocols.OSPF, 'Ljubjana', [PathReq(Protocols.OSPF, "Ljubjana", ['Brussels', 'Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Zagreb', 'Ljubjana'], False), PathReq(Protocols.OSPF, "Ljubjana", ['Brussels', 'Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Zagreb', 'Ljubjana'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Milan', [PathReq(Protocols.OSPF, "Milan", ['Brussels', 'Frankfurt', 'Vienna', 'Milan'], False), PathReq(Protocols.OSPF, "Milan", ['Brussels', 'Frankfurt', 'Zurich', 'Milan'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Basel', [PathReq(Protocols.OSPF, "Basel", ['Brussels', 'Luxembourg', 'Strasbourg', 'Basel'], False), PathReq(Protocols.OSPF, "Basel", ['Brussels', 'Frankfurt', 'Strasbourg', 'Basel'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Strasbourg', [PathReq(Protocols.OSPF, "Strasbourg", ['Brussels', 'Luxembourg', 'Strasbourg'], False), PathReq(Protocols.OSPF, "Strasbourg", ['Brussels', 'Frankfurt', 'Strasbourg'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Athens', [PathReq(Protocols.OSPF, "Athens", ['Brussels', 'Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Sofia', 'Athens'], False), PathReq(Protocols.OSPF, "Athens", ['Brussels', 'Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Sofia', 'Athens'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Zagreb', [PathReq(Protocols.OSPF, "Zagreb", ['Brussels', 'Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Zagreb'], False), PathReq(Protocols.OSPF, "Zagreb", ['Brussels', 'Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Zagreb'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Sofia', [PathReq(Protocols.OSPF, "Sofia", ['Brussels', 'Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Sofia'], False), PathReq(Protocols.OSPF, "Sofia", ['Brussels', 'Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Sofia'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Budapest', [PathReq(Protocols.OSPF, "Budapest", ['Brussels', 'Frankfurt', 'Vienna', 'Bratislava', 'Budapest'], False), PathReq(Protocols.OSPF, "Budapest", ['Brussels', 'Frankfurt', 'Praha', 'Bratislava', 'Budapest'], False)], False),
]

edges_cost_ecmp_8_2 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 2),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 1),
    ("Frankfurt", "Strasbourg", 1),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 2),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

reqs_kconnected_8_2 = [
    KConnectedPathsReq(Protocols.OSPF, 'Ljubjana', [PathReq(Protocols.OSPF, "Ljubjana", ['Brussels', 'Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Zagreb', 'Ljubjana'], False), PathReq(Protocols.OSPF, "Ljubjana", ['Brussels', 'Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Zagreb', 'Ljubjana'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Milan', [PathReq(Protocols.OSPF, "Milan", ['Brussels', 'Frankfurt', 'Vienna', 'Milan'], False), PathReq(Protocols.OSPF, "Milan", ['Brussels', 'Frankfurt', 'Zurich', 'Milan'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Basel', [PathReq(Protocols.OSPF, "Basel", ['Brussels', 'Luxembourg', 'Strasbourg', 'Basel'], False), PathReq(Protocols.OSPF, "Basel", ['Brussels', 'Frankfurt', 'Strasbourg', 'Basel'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Strasbourg', [PathReq(Protocols.OSPF, "Strasbourg", ['Brussels', 'Luxembourg', 'Strasbourg'], False), PathReq(Protocols.OSPF, "Strasbourg", ['Brussels', 'Frankfurt', 'Strasbourg'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Athens', [PathReq(Protocols.OSPF, "Athens", ['Brussels', 'Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Sofia', 'Athens'], False), PathReq(Protocols.OSPF, "Athens", ['Brussels', 'Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Sofia', 'Athens'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Zagreb', [PathReq(Protocols.OSPF, "Zagreb", ['Brussels', 'Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Zagreb'], False), PathReq(Protocols.OSPF, "Zagreb", ['Brussels', 'Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Zagreb'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Sofia', [PathReq(Protocols.OSPF, "Sofia", ['Brussels', 'Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Sofia'], False), PathReq(Protocols.OSPF, "Sofia", ['Brussels', 'Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Sofia'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Budapest', [PathReq(Protocols.OSPF, "Budapest", ['Brussels', 'Frankfurt', 'Vienna', 'Bratislava', 'Budapest'], False), PathReq(Protocols.OSPF, "Budapest", ['Brussels', 'Frankfurt', 'Praha', 'Bratislava', 'Budapest'], False)], False),
]

edges_cost_kconnected_8_2 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 2),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 1),
    ("Frankfurt", "Strasbourg", 1),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 2),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

reqs_order_8_2 = [
    PathOrderReq(Protocols.OSPF, 'Brussels', [PathReq(Protocols.OSPF, "Brussels", ['Luxembourg', 'Brussels'], False), PathReq(Protocols.OSPF, "Brussels", ['Luxembourg', 'Strasbourg', 'Frankfurt', 'Amsterdam', 'Brussels'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Paris', [PathReq(Protocols.OSPF, "Paris", ['Geneva', 'Paris'], False), PathReq(Protocols.OSPF, "Paris", ['Geneva', 'Lyon', 'Paris'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Luxembourg', [PathReq(Protocols.OSPF, "Luxembourg", ['Brussels', 'Luxembourg'], False), PathReq(Protocols.OSPF, "Luxembourg", ['Brussels', 'Frankfurt', 'Strasbourg', 'Luxembourg'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Madrid', [PathReq(Protocols.OSPF, "Madrid", ['Paris', 'Madrid'], False), PathReq(Protocols.OSPF, "Madrid", ['Paris', 'Lyon', 'Marseille', 'Barcelona', 'Madrid'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Geneva', [PathReq(Protocols.OSPF, "Geneva", ['Paris', 'Geneva'], False), PathReq(Protocols.OSPF, "Geneva", ['Paris', 'Lyon', 'Geneva'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Basel', [PathReq(Protocols.OSPF, "Basel", ['Geneva', 'Basel'], False), PathReq(Protocols.OSPF, "Basel", ['Geneva', 'Zurich', 'Frankfurt', 'Strasbourg', 'Basel'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Basel', [PathReq(Protocols.OSPF, "Basel", ['Strasbourg', 'Basel'], False), PathReq(Protocols.OSPF, "Basel", ['Strasbourg', 'Frankfurt', 'Amsterdam', 'Brussels', 'Paris', 'Geneva', 'Basel'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Frankfurt', [PathReq(Protocols.OSPF, "Frankfurt", ['Amsterdam', 'Frankfurt'], False), PathReq(Protocols.OSPF, "Frankfurt", ['Amsterdam', 'Brussels', 'Frankfurt'], False)], False),
]

edges_cost_order_8_2 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 1),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 2),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 3),
    ("Frankfurt", "Strasbourg", 1),
    ("Frankfurt", "Zurich", 4),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 1),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

reqs_simple_16 = [
    PathReq(Protocols.OSPF, "Sofia", ['Barcelona', 'Marseille', 'Milan', 'Vienna', 'Bratislava', 'Budapest', 'Sofia'], False),
    PathReq(Protocols.OSPF, "Rotterdam", ['Barcelona', 'Madrid', 'Paris', 'Brussels', 'Rotterdam'], False),
    PathReq(Protocols.OSPF, "Marseille", ['Barcelona', 'Marseille'], False),
    PathReq(Protocols.OSPF, "Vienna", ['Barcelona', 'Marseille', 'Milan', 'Vienna'], False),
    PathReq(Protocols.OSPF, "Frankfurt", ['Barcelona', 'Marseille', 'Milan', 'Zurich', 'Frankfurt'], False),
    PathReq(Protocols.OSPF, "Basel", ['Barcelona', 'Marseille', 'Lyon', 'Geneva', 'Basel'], False),
    PathReq(Protocols.OSPF, "Praha", ['Barcelona', 'Marseille', 'Milan', 'Vienna', 'Bratislava', 'Praha'], False),
    PathReq(Protocols.OSPF, "Zurich", ['Barcelona', 'Marseille', 'Milan', 'Zurich'], False),
    PathReq(Protocols.OSPF, "Istanbul", ['Barcelona', 'Marseille', 'Milan', 'Vienna', 'Bratislava', 'Budapest', 'Bucharest', 'Istanbul'], False),
    PathReq(Protocols.OSPF, "Brussels", ['Barcelona', 'Madrid', 'Paris', 'Brussels'], False),
    PathReq(Protocols.OSPF, "Dublin", ['Barcelona', 'Madrid', 'Paris', 'London', 'Dublin'], False),
    PathReq(Protocols.OSPF, "Ljubjana", ['Barcelona', 'Marseille', 'Milan', 'Vienna', 'Bratislava', 'Budapest', 'Zagreb', 'Ljubjana'], False),
    PathReq(Protocols.OSPF, "Madrid", ['Barcelona', 'Madrid'], False),
    PathReq(Protocols.OSPF, "Vaduz", ['Barcelona', 'Marseille', 'Milan', 'Zurich', 'Vaduz'], False),
    PathReq(Protocols.OSPF, "Budapest", ['Barcelona', 'Marseille', 'Milan', 'Vienna', 'Bratislava', 'Budapest'], False),
    PathReq(Protocols.OSPF, "Paris", ['Barcelona', 'Madrid', 'Paris'], False),
]

edges_cost_simple_16 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 2),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 2),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 2),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 1),
    ("Frankfurt", "Strasbourg", 1),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 2),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 1),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

####################

reqs_ecmp_16_2 = [
    ECMPPathsReq(Protocols.OSPF, 'Milan', [PathReq(Protocols.OSPF, "Milan", ['Frankfurt', 'Vienna', 'Milan'], False), PathReq(Protocols.OSPF, "Milan", ['Frankfurt', 'Zurich', 'Milan'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Marseille', [PathReq(Protocols.OSPF, "Marseille", ['Frankfurt', 'Vienna', 'Milan', 'Marseille'], False), PathReq(Protocols.OSPF, "Marseille", ['Frankfurt', 'Zurich', 'Milan', 'Marseille'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Sofia', [PathReq(Protocols.OSPF, "Sofia", ['Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Sofia'], False), PathReq(Protocols.OSPF, "Sofia", ['Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Sofia'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Budapest', [PathReq(Protocols.OSPF, "Budapest", ['Frankfurt', 'Praha', 'Bratislava', 'Budapest'], False), PathReq(Protocols.OSPF, "Budapest", ['Frankfurt', 'Vienna', 'Bratislava', 'Budapest'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Lisbon', [PathReq(Protocols.OSPF, "Lisbon", ['Frankfurt', 'Amsterdam', 'London', 'Lisbon'], False), PathReq(Protocols.OSPF, "Lisbon", ['Frankfurt', 'Brussels', 'London', 'Lisbon'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Ljubjana', [PathReq(Protocols.OSPF, "Ljubjana", ['Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Zagreb', 'Ljubjana'], False), PathReq(Protocols.OSPF, "Ljubjana", ['Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Zagreb', 'Ljubjana'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Lyon', [PathReq(Protocols.OSPF, "Lyon", ['Frankfurt', 'Brussels', 'Paris', 'Lyon'], False), PathReq(Protocols.OSPF, "Lyon", ['Frankfurt', 'Zurich', 'Geneva', 'Lyon'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Bratislava', [PathReq(Protocols.OSPF, "Bratislava", ['Frankfurt', 'Praha', 'Bratislava'], False), PathReq(Protocols.OSPF, "Bratislava", ['Frankfurt', 'Vienna', 'Bratislava'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'London', [PathReq(Protocols.OSPF, "London", ['Frankfurt', 'Amsterdam', 'London'], False), PathReq(Protocols.OSPF, "London", ['Frankfurt', 'Brussels', 'London'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Barcelona', [PathReq(Protocols.OSPF, "Barcelona", ['Frankfurt', 'Vienna', 'Milan', 'Marseille', 'Barcelona'], False), PathReq(Protocols.OSPF, "Barcelona", ['Frankfurt', 'Zurich', 'Milan', 'Marseille', 'Barcelona'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Rotterdam', [PathReq(Protocols.OSPF, "Rotterdam", ['Frankfurt', 'Amsterdam', 'Rotterdam'], False), PathReq(Protocols.OSPF, "Rotterdam", ['Frankfurt', 'Brussels', 'Rotterdam'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Bucharest', [PathReq(Protocols.OSPF, "Bucharest", ['Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Bucharest'], False), PathReq(Protocols.OSPF, "Bucharest", ['Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Bucharest'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Athens', [PathReq(Protocols.OSPF, "Athens", ['Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Sofia', 'Athens'], False), PathReq(Protocols.OSPF, "Athens", ['Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Sofia', 'Athens'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Zagreb', [PathReq(Protocols.OSPF, "Zagreb", ['Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Zagreb'], False), PathReq(Protocols.OSPF, "Zagreb", ['Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Zagreb'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Dublin', [PathReq(Protocols.OSPF, "Dublin", ['Frankfurt', 'Amsterdam', 'London', 'Dublin'], False), PathReq(Protocols.OSPF, "Dublin", ['Frankfurt', 'Brussels', 'London', 'Dublin'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Istanbul', [PathReq(Protocols.OSPF, "Istanbul", ['Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Bucharest', 'Istanbul'], False), PathReq(Protocols.OSPF, "Istanbul", ['Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Bucharest', 'Istanbul'], False)], False),
]

edges_cost_ecmp_16_2 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 2),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 1),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 1),
    ("Frankfurt", "Strasbourg", 1),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 3),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 2),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

reqs_kconnected_16_2 = [
    KConnectedPathsReq(Protocols.OSPF, 'Milan', [PathReq(Protocols.OSPF, "Milan", ['Frankfurt', 'Vienna', 'Milan'], False), PathReq(Protocols.OSPF, "Milan", ['Frankfurt', 'Zurich', 'Milan'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Marseille', [PathReq(Protocols.OSPF, "Marseille", ['Frankfurt', 'Vienna', 'Milan', 'Marseille'], False), PathReq(Protocols.OSPF, "Marseille", ['Frankfurt', 'Zurich', 'Milan', 'Marseille'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Sofia', [PathReq(Protocols.OSPF, "Sofia", ['Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Sofia'], False), PathReq(Protocols.OSPF, "Sofia", ['Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Sofia'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Budapest', [PathReq(Protocols.OSPF, "Budapest", ['Frankfurt', 'Praha', 'Bratislava', 'Budapest'], False), PathReq(Protocols.OSPF, "Budapest", ['Frankfurt', 'Vienna', 'Bratislava', 'Budapest'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Lisbon', [PathReq(Protocols.OSPF, "Lisbon", ['Frankfurt', 'Amsterdam', 'London', 'Lisbon'], False), PathReq(Protocols.OSPF, "Lisbon", ['Frankfurt', 'Brussels', 'London', 'Lisbon'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Ljubjana', [PathReq(Protocols.OSPF, "Ljubjana", ['Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Zagreb', 'Ljubjana'], False), PathReq(Protocols.OSPF, "Ljubjana", ['Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Zagreb', 'Ljubjana'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Lyon', [PathReq(Protocols.OSPF, "Lyon", ['Frankfurt', 'Brussels', 'Paris', 'Lyon'], False), PathReq(Protocols.OSPF, "Lyon", ['Frankfurt', 'Zurich', 'Geneva', 'Lyon'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Bratislava', [PathReq(Protocols.OSPF, "Bratislava", ['Frankfurt', 'Praha', 'Bratislava'], False), PathReq(Protocols.OSPF, "Bratislava", ['Frankfurt', 'Vienna', 'Bratislava'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'London', [PathReq(Protocols.OSPF, "London", ['Frankfurt', 'Amsterdam', 'London'], False), PathReq(Protocols.OSPF, "London", ['Frankfurt', 'Brussels', 'London'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Barcelona', [PathReq(Protocols.OSPF, "Barcelona", ['Frankfurt', 'Vienna', 'Milan', 'Marseille', 'Barcelona'], False), PathReq(Protocols.OSPF, "Barcelona", ['Frankfurt', 'Zurich', 'Milan', 'Marseille', 'Barcelona'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Rotterdam', [PathReq(Protocols.OSPF, "Rotterdam", ['Frankfurt', 'Amsterdam', 'Rotterdam'], False), PathReq(Protocols.OSPF, "Rotterdam", ['Frankfurt', 'Brussels', 'Rotterdam'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Bucharest', [PathReq(Protocols.OSPF, "Bucharest", ['Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Bucharest'], False), PathReq(Protocols.OSPF, "Bucharest", ['Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Bucharest'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Athens', [PathReq(Protocols.OSPF, "Athens", ['Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Sofia', 'Athens'], False), PathReq(Protocols.OSPF, "Athens", ['Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Sofia', 'Athens'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Zagreb', [PathReq(Protocols.OSPF, "Zagreb", ['Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Zagreb'], False), PathReq(Protocols.OSPF, "Zagreb", ['Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Zagreb'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Dublin', [PathReq(Protocols.OSPF, "Dublin", ['Frankfurt', 'Amsterdam', 'London', 'Dublin'], False), PathReq(Protocols.OSPF, "Dublin", ['Frankfurt', 'Brussels', 'London', 'Dublin'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Istanbul', [PathReq(Protocols.OSPF, "Istanbul", ['Frankfurt', 'Praha', 'Bratislava', 'Budapest', 'Bucharest', 'Istanbul'], False), PathReq(Protocols.OSPF, "Istanbul", ['Frankfurt', 'Vienna', 'Bratislava', 'Budapest', 'Bucharest', 'Istanbul'], False)], False),
]

edges_cost_kconnected_16_2 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 1),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 1),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 2),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 2),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 1),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 1),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 2),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 1),
    ("Frankfurt", "Strasbourg", 2),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 3),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 1),
    ("Zurich", "Frankfurt", 1),
    ("Zurich", "Geneva", 1),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 1),
    ("Praha", "Warsaw", 2),
    ("London", "Paris", 2),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 1),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

reqs_order_16_2 = [
    PathOrderReq(Protocols.OSPF, 'Bratislava', [PathReq(Protocols.OSPF, "Bratislava", ['Budapest', 'Bratislava'], False), PathReq(Protocols.OSPF, "Bratislava", ['Budapest', 'Bucharest', 'Kiev', 'Warsaw', 'Praha', 'Bratislava'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Zurich', [PathReq(Protocols.OSPF, "Zurich", ['Roma', 'Zurich'], False), PathReq(Protocols.OSPF, "Zurich", ['Roma', 'Milan', 'Zurich'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Paris', [PathReq(Protocols.OSPF, "Paris", ['Lyon', 'Paris'], False), PathReq(Protocols.OSPF, "Paris", ['Lyon', 'Geneva', 'Paris'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Amsterdam', [PathReq(Protocols.OSPF, "Amsterdam", ['Brussels', 'Amsterdam'], False), PathReq(Protocols.OSPF, "Amsterdam", ['Brussels', 'London', 'Amsterdam'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Strasbourg', [PathReq(Protocols.OSPF, "Strasbourg", ['Luxembourg', 'Strasbourg'], False), PathReq(Protocols.OSPF, "Strasbourg", ['Luxembourg', 'Brussels', 'Frankfurt', 'Strasbourg'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Rotterdam', [PathReq(Protocols.OSPF, "Rotterdam", ['Amsterdam', 'Rotterdam'], False), PathReq(Protocols.OSPF, "Rotterdam", ['Amsterdam', 'London', 'Brussels', 'Rotterdam'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Barcelona', [PathReq(Protocols.OSPF, "Barcelona", ['Marseille', 'Barcelona'], False), PathReq(Protocols.OSPF, "Barcelona", ['Marseille', 'Lyon', 'Paris', 'Madrid', 'Barcelona'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Milan', [PathReq(Protocols.OSPF, "Milan", ['Vienna', 'Milan'], False), PathReq(Protocols.OSPF, "Milan", ['Vienna', 'Frankfurt', 'Zurich', 'Roma', 'Milan'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Lyon', [PathReq(Protocols.OSPF, "Lyon", ['Paris', 'Lyon'], False), PathReq(Protocols.OSPF, "Lyon", ['Paris', 'Geneva', 'Lyon'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Luxembourg', [PathReq(Protocols.OSPF, "Luxembourg", ['Strasbourg', 'Luxembourg'], False), PathReq(Protocols.OSPF, "Luxembourg", ['Strasbourg', 'Basel', 'Geneva', 'Paris', 'Brussels', 'Luxembourg'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Paris', [PathReq(Protocols.OSPF, "Paris", ['London', 'Paris'], False), PathReq(Protocols.OSPF, "Paris", ['London', 'Brussels', 'Paris'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Bratislava', [PathReq(Protocols.OSPF, "Bratislava", ['Praha', 'Bratislava'], False), PathReq(Protocols.OSPF, "Bratislava", ['Praha', 'Warsaw', 'Frankfurt', 'Vienna', 'Bratislava'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Geneva', [PathReq(Protocols.OSPF, "Geneva", ['Basel', 'Geneva'], False), PathReq(Protocols.OSPF, "Geneva", ['Basel', 'Strasbourg', 'Frankfurt', 'Amsterdam', 'London', 'Paris', 'Geneva'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Barcelona', [PathReq(Protocols.OSPF, "Barcelona", ['Madrid', 'Barcelona'], False), PathReq(Protocols.OSPF, "Barcelona", ['Madrid', 'Paris', 'Lyon', 'Marseille', 'Barcelona'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Istanbul', [PathReq(Protocols.OSPF, "Istanbul", ['Bucharest', 'Istanbul'], False), PathReq(Protocols.OSPF, "Istanbul", ['Bucharest', 'Budapest', 'Sofia', 'Athens', 'Istanbul'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Frankfurt', [PathReq(Protocols.OSPF, "Frankfurt", ['Vienna', 'Frankfurt'], False), PathReq(Protocols.OSPF, "Frankfurt", ['Vienna', 'Bratislava', 'Praha', 'Warsaw', 'Frankfurt'], False)], False),
]

edges_cost_order_16_2 = [
    ("Lyon", "Paris", 1),
    ("Lyon", "Marseille", 1),
    ("Lyon", "Geneva", 1),
    ("Kiev", "Bucharest", 1),
    ("Kiev", "Warsaw", 1),
    ("Istanbul", "Bucharest", 1),
    ("Istanbul", "Athens", 1),
    ("Paris", "Madrid", 1),
    ("Paris", "Lyon", 1),
    ("Paris", "Brussels", 1),
    ("Paris", "London", 1),
    ("Paris", "Geneva", 1),
    ("Basel", "Geneva", 1),
    ("Basel", "Strasbourg", 1),
    ("Athens", "Sofia", 1),
    ("Athens", "Istanbul", 1),
    ("Luxembourg", "Brussels", 1),
    ("Luxembourg", "Strasbourg", 1),
    ("Rotterdam", "Amsterdam", 2),
    ("Rotterdam", "Brussels", 1),
    ("Vienna", "Milan", 1),
    ("Vienna", "Frankfurt", 1),
    ("Vienna", "Bratislava", 1),
    ("Ljubjana", "Zagreb", 1),
    ("Geneva", "Paris", 1),
    ("Geneva", "Lyon", 1),
    ("Geneva", "Basel", 1),
    ("Geneva", "Zurich", 1),
    ("Zagreb", "Budapest", 1),
    ("Zagreb", "Ljubjana", 1),
    ("Bratislava", "Budapest", 1),
    ("Bratislava", "Praha", 1),
    ("Bratislava", "Vienna", 1),
    ("Brussels", "Paris", 1),
    ("Brussels", "Luxembourg", 1),
    ("Brussels", "London", 1),
    ("Brussels", "Amsterdam", 1),
    ("Brussels", "Rotterdam", 1),
    ("Brussels", "Frankfurt", 2),
    ("Strasbourg", "Basel", 1),
    ("Strasbourg", "Frankfurt", 1),
    ("Strasbourg", "Luxembourg", 3),
    ("Budapest", "Bucharest", 1),
    ("Budapest", "Zagreb", 1),
    ("Budapest", "Sofia", 1),
    ("Budapest", "Bratislava", 1),
    ("Vaduz", "Zurich", 1),
    ("Dublin", "London", 1),
    ("Barcelona", "Madrid", 1),
    ("Barcelona", "Marseille", 1),
    ("Stockholm", "Frankfurt", 1),
    ("Roma", "Milan", 1),
    ("Roma", "Zurich", 1),
    ("Marseille", "Milan", 1),
    ("Marseille", "Lyon", 1),
    ("Marseille", "Barcelona", 1),
    ("Frankfurt", "Brussels", 4),
    ("Frankfurt", "Strasbourg", 1),
    ("Frankfurt", "Zurich", 1),
    ("Frankfurt", "Praha", 1),
    ("Frankfurt", "Stockholm", 1),
    ("Frankfurt", "Amsterdam", 1),
    ("Frankfurt", "Warsaw", 1),
    ("Frankfurt", "Vienna", 1),
    ("Bucharest", "Budapest", 1),
    ("Bucharest", "Kiev", 1),
    ("Bucharest", "Istanbul", 1),
    ("Zurich", "Vaduz", 1),
    ("Zurich", "Milan", 3),
    ("Zurich", "Frankfurt", 3),
    ("Zurich", "Geneva", 4),
    ("Zurich", "Roma", 1),
    ("Madrid", "Paris", 1),
    ("Madrid", "Barcelona", 1),
    ("Sofia", "Budapest", 1),
    ("Sofia", "Athens", 1),
    ("Milan", "Zurich", 1),
    ("Milan", "Marseille", 1),
    ("Milan", "Roma", 1),
    ("Milan", "Vienna", 1),
    ("Praha", "Bratislava", 1),
    ("Praha", "Frankfurt", 3),
    ("Praha", "Warsaw", 1),
    ("London", "Paris", 1),
    ("London", "Amsterdam", 1),
    ("London", "Brussels", 1),
    ("London", "Dublin", 1),
    ("London", "Lisbon", 1),
    ("Lisbon", "London", 1),
    ("Amsterdam", "Brussels", 3),
    ("Amsterdam", "Rotterdam", 1),
    ("Amsterdam", "Frankfurt", 1),
    ("Amsterdam", "London", 1),
    ("Warsaw", "Praha", 1),
    ("Warsaw", "Frankfurt", 1),
    ("Warsaw", "Kiev", 1),
]

####################

reqs_simple = [reqs_simple_1,reqs_simple_2,reqs_simple_4,reqs_simple_8,reqs_simple_16]

reqs_simple_vals = [edges_cost_simple_1,edges_cost_simple_2,edges_cost_simple_4,edges_cost_simple_8,edges_cost_simple_16]

####################

reqs_ecmp = [reqs_ecmp_1_2,reqs_ecmp_2_2,reqs_ecmp_4_2,reqs_ecmp_8_2,reqs_ecmp_16_2]

reqs_ecmp_vals = [edges_cost_ecmp_1_2,edges_cost_ecmp_2_2,edges_cost_ecmp_4_2,edges_cost_ecmp_8_2,edges_cost_ecmp_16_2]

####################

reqs_kconnected = [reqs_kconnected_1_2,reqs_kconnected_2_2,reqs_kconnected_4_2,reqs_kconnected_8_2,reqs_kconnected_16_2]

reqs_kconnected_vals = [edges_cost_kconnected_1_2,edges_cost_kconnected_2_2,edges_cost_kconnected_4_2,edges_cost_kconnected_8_2,edges_cost_kconnected_16_2]

####################

reqs_order = [reqs_order_1_2, reqs_order_2_2, reqs_order_4_2, reqs_order_8_2, reqs_order_16_2]

reqs_order_vals = [edges_cost_order_1_2, edges_cost_order_2_2, edges_cost_order_4_2, edges_cost_order_8_2, edges_cost_order_16_2]

####################

