from synet.utils.common import PathReq
from synet.utils.common import ECMPPathsReq
from synet.utils.common import PathOrderReq
from synet.utils.common import Protocols
from synet.utils.common import KConnectedPathsReq


topology_file = 'topos/small/Canerie.graphml'
seed = 2789802747494003747
reqs_simple_1 = [
    PathReq(Protocols.OSPF, "Windsor/Detroit", ['Regina', 'Calgary', 'Chicago', 'Windsor/Detroit'], False),
]

edges_cost_simple_1 = [
    ("Toronto", "Windsor/Detroit", 1),
    ("Toronto", "NewTTYork", 1),
    ("Toronto", "Winnipeg", 1),
    ("Toronto", "Ottawa", 1),
    ("Toronto", "ThunderTTBay", 1),
    ("Regina", "Calgary", 1),
    ("Regina", "Winnipeg", 1),
    ("EuropeTTetTTautresTTpays", "NewTTYork", 1),
    ("Kelowna", "Kamloops", 1),
    ("Chicago", "NorthTTandTTSouthTTAmerica", 1),
    ("Chicago", "Winnipeg", 1),
    ("Chicago", "Windsor/Detroit", 1),
    ("Chicago", "Calgary", 1),
    ("Chicago", "EuropeTTandTTotherTTcountriesID19", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "AmeriqueTTduTTNordTTetTTAmeriqueTTduTTSud", 1),
    ("Whitehorse", "Edmonton", 1),
    ("Winnipeg", "Toronto", 2),
    ("Winnipeg", "Regina", 1),
    ("Winnipeg", "Chicago", 2),
    ("Winnipeg", "Saskatoon", 1),
    ("Winnipeg", "Calgary", 1),
    ("Winnipeg", "ThunderTTBay", 1),
    ("Vancouver", "Seattle", 1),
    ("Vancouver", "Kamloops", 1),
    ("Vancouver", "Victoria", 1),
    ("Calgary", "Edmonton", 1),
    ("Calgary", "Winnipeg", 1),
    ("Calgary", "Regina", 1),
    ("Calgary", "Kamloops", 1),
    ("Calgary", "Chicago", 1),
    ("EuropeTTandTTotherTTcountriesID19", "Chicago", 1),
    ("StTTJohn's", "Europe", 1),
    ("StTTJohn's", "Halifax", 1),
    ("ThunderTTBay", "Toronto", 1),
    ("ThunderTTBay", "Winnipeg", 1),
    ("Europe", "StTTJohn's", 1),
    ("Charlottetown", "Halifax", 1),
    ("Charlottetown", "Fredericton", 1),
    ("Fredericton", "Charlottetown", 1),
    ("Fredericton", "Montreal", 1),
    ("NewTTYork", "EuropeTTandTTotherTTcountries", 1),
    ("NewTTYork", "Toronto", 1),
    ("NewTTYork", "Halifax", 1),
    ("NewTTYork", "EuropeTTetTTautresTTpays", 1),
    ("NewTTYork", "Boston", 1),
    ("Victoria", "Seattle", 1),
    ("Victoria", "Vancouver", 1),
    ("Asia-Pacific", "Seattle", 1),
    ("AmeriqueTTduTTNordTTetTTAmeriqueTTduTTSud", "Chicago", 1),
    ("EuropeTTandTTotherTTcountries", "NewTTYork", 1),
    ("Yellowknife", "Edmonton", 1),
    ("Saskatoon", "Edmonton", 1),
    ("Saskatoon", "Winnipeg", 1),
    ("Ottawa", "Toronto", 1),
    ("Ottawa", "Montreal", 1),
    ("Windsor/Detroit", "Toronto", 1),
    ("Windsor/Detroit", "Chicago", 1),
    ("Halifax", "Charlottetown", 1),
    ("Halifax", "StTTJohn's", 1),
    ("Halifax", "NewTTYork", 1),
    ("Halifax", "Montreal", 1),
    ("Montreal", "Boston", 1),
    ("Montreal", "Halifax", 1),
    ("Montreal", "Ottawa", 1),
    ("Montreal", "Fredericton", 1),
    ("Kamloops", "Calgary", 1),
    ("Kamloops", "Vancouver", 1),
    ("Kamloops", "Kelowna", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Montreal", 1),
    ("Edmonton", "Whitehorse", 1),
    ("Edmonton", "Yellowknife", 1),
    ("Edmonton", "Saskatoon", 1),
    ("Edmonton", "Calgary", 1),
    ("NorthTTandTTSouthTTAmerica", "Chicago", 1),
    ("Asie-Pacifique", "Seattle", 1),
    ("Seattle", "Asia-Pacific", 1),
    ("Seattle", "Asie-Pacifique", 1),
    ("Seattle", "Victoria", 1),
    ("Seattle", "Vancouver", 1),
    ("Seattle", "Chicago", 1),
]

reqs_simple = [reqs_simple_1]

reqs_simple_vals = [edges_cost_simple_1]

####################

reqs_ecmp_1_2 = [
    ECMPPathsReq(Protocols.OSPF, 'Halifax', [PathReq(Protocols.OSPF, "Halifax", ['Chicago', 'Windsor/Detroit', 'Toronto', 'NewTTYork', 'Halifax'], False), PathReq(Protocols.OSPF, "Halifax", ['Chicago', 'Winnipeg', 'Toronto', 'NewTTYork', 'Halifax'], False)], False),
]

edges_cost_ecmp_1_2 = [
    ("Toronto", "Windsor/Detroit", 1),
    ("Toronto", "NewTTYork", 1),
    ("Toronto", "Winnipeg", 1),
    ("Toronto", "Ottawa", 1),
    ("Toronto", "ThunderTTBay", 1),
    ("Regina", "Calgary", 1),
    ("Regina", "Winnipeg", 1),
    ("EuropeTTetTTautresTTpays", "NewTTYork", 1),
    ("Kelowna", "Kamloops", 1),
    ("Chicago", "NorthTTandTTSouthTTAmerica", 1),
    ("Chicago", "Winnipeg", 1),
    ("Chicago", "Windsor/Detroit", 1),
    ("Chicago", "Calgary", 1),
    ("Chicago", "EuropeTTandTTotherTTcountriesID19", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "AmeriqueTTduTTNordTTetTTAmeriqueTTduTTSud", 1),
    ("Whitehorse", "Edmonton", 1),
    ("Winnipeg", "Toronto", 1),
    ("Winnipeg", "Regina", 1),
    ("Winnipeg", "Chicago", 1),
    ("Winnipeg", "Saskatoon", 1),
    ("Winnipeg", "Calgary", 1),
    ("Winnipeg", "ThunderTTBay", 1),
    ("Vancouver", "Seattle", 1),
    ("Vancouver", "Kamloops", 1),
    ("Vancouver", "Victoria", 1),
    ("Calgary", "Edmonton", 1),
    ("Calgary", "Winnipeg", 1),
    ("Calgary", "Regina", 1),
    ("Calgary", "Kamloops", 1),
    ("Calgary", "Chicago", 1),
    ("EuropeTTandTTotherTTcountriesID19", "Chicago", 1),
    ("StTTJohn's", "Europe", 1),
    ("StTTJohn's", "Halifax", 1),
    ("ThunderTTBay", "Toronto", 1),
    ("ThunderTTBay", "Winnipeg", 1),
    ("Europe", "StTTJohn's", 1),
    ("Charlottetown", "Halifax", 1),
    ("Charlottetown", "Fredericton", 1),
    ("Fredericton", "Charlottetown", 1),
    ("Fredericton", "Montreal", 1),
    ("NewTTYork", "EuropeTTandTTotherTTcountries", 1),
    ("NewTTYork", "Toronto", 1),
    ("NewTTYork", "Halifax", 1),
    ("NewTTYork", "EuropeTTetTTautresTTpays", 1),
    ("NewTTYork", "Boston", 1),
    ("Victoria", "Seattle", 1),
    ("Victoria", "Vancouver", 1),
    ("Asia-Pacific", "Seattle", 1),
    ("AmeriqueTTduTTNordTTetTTAmeriqueTTduTTSud", "Chicago", 1),
    ("EuropeTTandTTotherTTcountries", "NewTTYork", 1),
    ("Yellowknife", "Edmonton", 1),
    ("Saskatoon", "Edmonton", 1),
    ("Saskatoon", "Winnipeg", 1),
    ("Ottawa", "Toronto", 1),
    ("Ottawa", "Montreal", 1),
    ("Windsor/Detroit", "Toronto", 1),
    ("Windsor/Detroit", "Chicago", 1),
    ("Halifax", "Charlottetown", 1),
    ("Halifax", "StTTJohn's", 1),
    ("Halifax", "NewTTYork", 1),
    ("Halifax", "Montreal", 1),
    ("Montreal", "Boston", 1),
    ("Montreal", "Halifax", 1),
    ("Montreal", "Ottawa", 1),
    ("Montreal", "Fredericton", 1),
    ("Kamloops", "Calgary", 1),
    ("Kamloops", "Vancouver", 1),
    ("Kamloops", "Kelowna", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Montreal", 1),
    ("Edmonton", "Whitehorse", 1),
    ("Edmonton", "Yellowknife", 1),
    ("Edmonton", "Saskatoon", 1),
    ("Edmonton", "Calgary", 1),
    ("NorthTTandTTSouthTTAmerica", "Chicago", 1),
    ("Asie-Pacifique", "Seattle", 1),
    ("Seattle", "Asia-Pacific", 1),
    ("Seattle", "Asie-Pacifique", 1),
    ("Seattle", "Victoria", 1),
    ("Seattle", "Vancouver", 1),
    ("Seattle", "Chicago", 1),
]

reqs_ecmp = [reqs_ecmp_1_2]

reqs_ecmp_vals = [edges_cost_ecmp_1_2]

####################

reqs_kconnected_1_2 = [
    KConnectedPathsReq(Protocols.OSPF, 'Halifax', [PathReq(Protocols.OSPF, "Halifax", ['Chicago', 'Windsor/Detroit', 'Toronto', 'NewTTYork', 'Halifax'], False), PathReq(Protocols.OSPF, "Halifax", ['Chicago', 'Winnipeg', 'Toronto', 'NewTTYork', 'Halifax'], False)], False),
]

edges_cost_kconnected_1_2 = [
    ("Toronto", "Windsor/Detroit", 1),
    ("Toronto", "NewTTYork", 1),
    ("Toronto", "Winnipeg", 1),
    ("Toronto", "Ottawa", 1),
    ("Toronto", "ThunderTTBay", 1),
    ("Regina", "Calgary", 1),
    ("Regina", "Winnipeg", 1),
    ("EuropeTTetTTautresTTpays", "NewTTYork", 1),
    ("Kelowna", "Kamloops", 1),
    ("Chicago", "NorthTTandTTSouthTTAmerica", 1),
    ("Chicago", "Winnipeg", 1),
    ("Chicago", "Windsor/Detroit", 1),
    ("Chicago", "Calgary", 1),
    ("Chicago", "EuropeTTandTTotherTTcountriesID19", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "AmeriqueTTduTTNordTTetTTAmeriqueTTduTTSud", 1),
    ("Whitehorse", "Edmonton", 1),
    ("Winnipeg", "Toronto", 1),
    ("Winnipeg", "Regina", 1),
    ("Winnipeg", "Chicago", 1),
    ("Winnipeg", "Saskatoon", 1),
    ("Winnipeg", "Calgary", 1),
    ("Winnipeg", "ThunderTTBay", 1),
    ("Vancouver", "Seattle", 1),
    ("Vancouver", "Kamloops", 1),
    ("Vancouver", "Victoria", 1),
    ("Calgary", "Edmonton", 1),
    ("Calgary", "Winnipeg", 1),
    ("Calgary", "Regina", 1),
    ("Calgary", "Kamloops", 1),
    ("Calgary", "Chicago", 1),
    ("EuropeTTandTTotherTTcountriesID19", "Chicago", 1),
    ("StTTJohn's", "Europe", 1),
    ("StTTJohn's", "Halifax", 1),
    ("ThunderTTBay", "Toronto", 1),
    ("ThunderTTBay", "Winnipeg", 1),
    ("Europe", "StTTJohn's", 1),
    ("Charlottetown", "Halifax", 1),
    ("Charlottetown", "Fredericton", 1),
    ("Fredericton", "Charlottetown", 1),
    ("Fredericton", "Montreal", 1),
    ("NewTTYork", "EuropeTTandTTotherTTcountries", 1),
    ("NewTTYork", "Toronto", 1),
    ("NewTTYork", "Halifax", 1),
    ("NewTTYork", "EuropeTTetTTautresTTpays", 1),
    ("NewTTYork", "Boston", 1),
    ("Victoria", "Seattle", 1),
    ("Victoria", "Vancouver", 1),
    ("Asia-Pacific", "Seattle", 1),
    ("AmeriqueTTduTTNordTTetTTAmeriqueTTduTTSud", "Chicago", 1),
    ("EuropeTTandTTotherTTcountries", "NewTTYork", 1),
    ("Yellowknife", "Edmonton", 1),
    ("Saskatoon", "Edmonton", 1),
    ("Saskatoon", "Winnipeg", 1),
    ("Ottawa", "Toronto", 1),
    ("Ottawa", "Montreal", 1),
    ("Windsor/Detroit", "Toronto", 1),
    ("Windsor/Detroit", "Chicago", 1),
    ("Halifax", "Charlottetown", 1),
    ("Halifax", "StTTJohn's", 1),
    ("Halifax", "NewTTYork", 1),
    ("Halifax", "Montreal", 1),
    ("Montreal", "Boston", 1),
    ("Montreal", "Halifax", 1),
    ("Montreal", "Ottawa", 1),
    ("Montreal", "Fredericton", 1),
    ("Kamloops", "Calgary", 1),
    ("Kamloops", "Vancouver", 1),
    ("Kamloops", "Kelowna", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Montreal", 1),
    ("Edmonton", "Whitehorse", 1),
    ("Edmonton", "Yellowknife", 1),
    ("Edmonton", "Saskatoon", 1),
    ("Edmonton", "Calgary", 1),
    ("NorthTTandTTSouthTTAmerica", "Chicago", 1),
    ("Asie-Pacifique", "Seattle", 1),
    ("Seattle", "Asia-Pacific", 1),
    ("Seattle", "Asie-Pacifique", 1),
    ("Seattle", "Victoria", 1),
    ("Seattle", "Vancouver", 1),
    ("Seattle", "Chicago", 1),
]

reqs_kconnected = [reqs_kconnected_1_2]

reqs_kconnected_vals = [edges_cost_kconnected_1_2]

####################

