
from synet.utils.common import PathReq
from synet.utils.common import ECMPPathsReq
from synet.utils.common import PathOrderReq
from synet.utils.common import Protocols
from synet.utils.common import KConnectedPathsReq

topology_file = 'topos/small/CrlNetworkServices.graphml'
seed = 3923389501
reqs_simple_1 = [
    PathReq(Protocols.OSPF, "Stockton", ['Albuquerque', 'Dallas', 'StTTLouis', 'Chicago', 'Seattle', 'Portland', 'SantaTTRosa', 'Sacramento', 'Stockton'], False),
]

edges_cost_simple_1 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 3),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 1),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 2),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

####################

reqs_ecmp_1_2 = [
    ECMPPathsReq(Protocols.OSPF, 'Anaheim', [PathReq(Protocols.OSPF, "Anaheim", ['Seattle', 'Portland', 'SantaTTRosa', 'SanTTRafael', 'SanTTFrancisco', 'SanTTJose', 'LosTTAngeles', 'Anaheim'], False), PathReq(Protocols.OSPF, "Anaheim", ['Seattle', 'Chicago', 'StTTLouis', 'Dallas', 'Albuquerque', 'Phoenix', 'SanTTDiego', 'Anaheim'], False)], False),
]

edges_cost_ecmp_1_2 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 1),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

reqs_kconnected_1_2 = [
    KConnectedPathsReq(Protocols.OSPF, 'Anaheim', [PathReq(Protocols.OSPF, "Anaheim", ['Seattle', 'Portland', 'SantaTTRosa', 'SanTTRafael', 'SanTTFrancisco', 'SanTTJose', 'LosTTAngeles', 'Anaheim'], False), PathReq(Protocols.OSPF, "Anaheim", ['Seattle', 'Chicago', 'StTTLouis', 'Dallas', 'Albuquerque', 'Phoenix', 'SanTTDiego', 'Anaheim'], False)], False),
]

edges_cost_kconnected_1_2 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 1),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

reqs_order_1_2 = [
    PathOrderReq(Protocols.OSPF, 'Baltimore', [PathReq(Protocols.OSPF, "Baltimore", ['Philadelphia', 'Baltimore'], False), PathReq(Protocols.OSPF, "Baltimore", ['Philadelphia', 'NewTTYork', 'Boston', 'Cleveland', 'Pittsburgh', 'Washington,TTDC', 'Baltimore'], False)], False),
]

edges_cost_order_1_2 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 1),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

reqs_simple_2 = [
    PathReq(Protocols.OSPF, "Dallas", ['Austin', 'Dallas'], False),
    PathReq(Protocols.OSPF, "Denver", ['Austin', 'Dallas', 'StTTLouis', 'KansasTTCity', 'Denver'], False),
]

edges_cost_simple_2 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 1),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

####################

reqs_ecmp_2_2 = [
    ECMPPathsReq(Protocols.OSPF, 'Sacramento', [PathReq(Protocols.OSPF, "Sacramento", ['Houston', 'Dallas', 'StTTLouis', 'Chicago', 'Seattle', 'Portland', 'SantaTTRosa', 'Sacramento'], False), PathReq(Protocols.OSPF, "Sacramento", ['Houston', 'Dallas', 'StTTLouis', 'KansasTTCity', 'Denver', 'SanTTFrancisco', 'Concord', 'Stockton', 'Sacramento'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Austin', [PathReq(Protocols.OSPF, "Austin", ['Houston', 'Dallas', 'Austin'], False), PathReq(Protocols.OSPF, "Austin", ['Houston', 'SanTTAntonio', 'Austin'], False)], False),
]

edges_cost_ecmp_2_2 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 2),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 1),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

reqs_kconnected_2_2 = [
    KConnectedPathsReq(Protocols.OSPF, 'Sacramento', [PathReq(Protocols.OSPF, "Sacramento", ['Houston', 'Dallas', 'StTTLouis', 'Chicago', 'Seattle', 'Portland', 'SantaTTRosa', 'Sacramento'], False), PathReq(Protocols.OSPF, "Sacramento", ['Houston', 'Dallas', 'StTTLouis', 'KansasTTCity', 'Denver', 'SanTTFrancisco', 'Concord', 'Stockton', 'Sacramento'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Austin', [PathReq(Protocols.OSPF, "Austin", ['Houston', 'Dallas', 'Austin'], False), PathReq(Protocols.OSPF, "Austin", ['Houston', 'SanTTAntonio', 'Austin'], False)], False),
]

edges_cost_kconnected_2_2 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 1),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 2),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

reqs_order_2_2 = [
    PathOrderReq(Protocols.OSPF, 'Sacramento', [PathReq(Protocols.OSPF, "Sacramento", ['SantaTTRosa', 'Sacramento'], False), PathReq(Protocols.OSPF, "Sacramento", ['SantaTTRosa', 'SanTTRafael', 'SanTTFrancisco', 'Concord', 'Stockton', 'Sacramento'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Stockton', [PathReq(Protocols.OSPF, "Stockton", ['Concord', 'Stockton'], False), PathReq(Protocols.OSPF, "Stockton", ['Concord', 'SanTTFrancisco', 'SanTTRafael', 'SantaTTRosa', 'Sacramento', 'Stockton'], False)], False),
]

edges_cost_order_2_2 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 1),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

reqs_simple_4 = [
    PathReq(Protocols.OSPF, "SanTTRafael", ['Seattle', 'Portland', 'SantaTTRosa', 'SanTTRafael'], False),
    PathReq(Protocols.OSPF, "Boston", ['Seattle', 'Chicago', 'Detroit', 'Cleveland', 'Boston'], False),
    PathReq(Protocols.OSPF, "SanTTAntonio", ['Seattle', 'Chicago', 'StTTLouis', 'Dallas', 'Austin', 'SanTTAntonio'], False),
    PathReq(Protocols.OSPF, "Albuquerque", ['Seattle', 'Chicago', 'StTTLouis', 'Dallas', 'Albuquerque'], False),
]

edges_cost_simple_4 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 2),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

####################

reqs_ecmp_4_2 = [
    ECMPPathsReq(Protocols.OSPF, 'Seattle', [PathReq(Protocols.OSPF, "Seattle", ['SanTTJose', 'SanTTFrancisco', 'Denver', 'KansasTTCity', 'StTTLouis', 'Chicago', 'Seattle'], False), PathReq(Protocols.OSPF, "Seattle", ['SanTTJose', 'SanTTFrancisco', 'SanTTRafael', 'SantaTTRosa', 'Portland', 'Seattle'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Sacramento', [PathReq(Protocols.OSPF, "Sacramento", ['SanTTJose', 'SanTTFrancisco', 'SanTTRafael', 'SantaTTRosa', 'Sacramento'], False), PathReq(Protocols.OSPF, "Sacramento", ['SanTTJose', 'SanTTFrancisco', 'Concord', 'Stockton', 'Sacramento'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Philadelphia', [PathReq(Protocols.OSPF, "Philadelphia", ['SanTTJose', 'SanTTFrancisco', 'Denver', 'KansasTTCity', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland', 'Boston', 'NewTTYork', 'Philadelphia'], False), PathReq(Protocols.OSPF, "Philadelphia", ['SanTTJose', 'SanTTFrancisco', 'Denver', 'KansasTTCity', 'StTTLouis', 'Dallas', 'Atlanta', 'Raleigh', 'Washington,TTDC', 'Baltimore', 'Philadelphia'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'SanTTAntonio', [PathReq(Protocols.OSPF, "SanTTAntonio", ['SanTTJose', 'SanTTFrancisco', 'Denver', 'KansasTTCity', 'StTTLouis', 'Dallas', 'Austin', 'SanTTAntonio'], False), PathReq(Protocols.OSPF, "SanTTAntonio", ['SanTTJose', 'SanTTFrancisco', 'Denver', 'KansasTTCity', 'StTTLouis', 'Dallas', 'Houston', 'SanTTAntonio'], False)], False),
]

edges_cost_ecmp_4_2 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 1),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 2),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 2),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

reqs_kconnected_4_2 = [
    KConnectedPathsReq(Protocols.OSPF, 'Seattle', [PathReq(Protocols.OSPF, "Seattle", ['SanTTJose', 'SanTTFrancisco', 'Denver', 'KansasTTCity', 'StTTLouis', 'Chicago', 'Seattle'], False), PathReq(Protocols.OSPF, "Seattle", ['SanTTJose', 'SanTTFrancisco', 'SanTTRafael', 'SantaTTRosa', 'Portland', 'Seattle'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Sacramento', [PathReq(Protocols.OSPF, "Sacramento", ['SanTTJose', 'SanTTFrancisco', 'SanTTRafael', 'SantaTTRosa', 'Sacramento'], False), PathReq(Protocols.OSPF, "Sacramento", ['SanTTJose', 'SanTTFrancisco', 'Concord', 'Stockton', 'Sacramento'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Philadelphia', [PathReq(Protocols.OSPF, "Philadelphia", ['SanTTJose', 'SanTTFrancisco', 'Denver', 'KansasTTCity', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland', 'Boston', 'NewTTYork', 'Philadelphia'], False), PathReq(Protocols.OSPF, "Philadelphia", ['SanTTJose', 'SanTTFrancisco', 'Denver', 'KansasTTCity', 'StTTLouis', 'Dallas', 'Atlanta', 'Raleigh', 'Washington,TTDC', 'Baltimore', 'Philadelphia'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'SanTTAntonio', [PathReq(Protocols.OSPF, "SanTTAntonio", ['SanTTJose', 'SanTTFrancisco', 'Denver', 'KansasTTCity', 'StTTLouis', 'Dallas', 'Austin', 'SanTTAntonio'], False), PathReq(Protocols.OSPF, "SanTTAntonio", ['SanTTJose', 'SanTTFrancisco', 'Denver', 'KansasTTCity', 'StTTLouis', 'Dallas', 'Houston', 'SanTTAntonio'], False)], False),
]

edges_cost_kconnected_4_2 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 1),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

reqs_order_4_2 = [
    PathOrderReq(Protocols.OSPF, 'StTTLouis', [PathReq(Protocols.OSPF, "StTTLouis", ['KansasTTCity', 'StTTLouis'], False), PathReq(Protocols.OSPF, "StTTLouis", ['KansasTTCity', 'Denver', 'SanTTFrancisco', 'SanTTRafael', 'SantaTTRosa', 'Portland', 'Seattle', 'Chicago', 'StTTLouis'], False)], False),
    PathOrderReq(Protocols.OSPF, 'SanTTDiego', [PathReq(Protocols.OSPF, "SanTTDiego", ['Anaheim', 'SanTTDiego'], False), PathReq(Protocols.OSPF, "SanTTDiego", ['Anaheim', 'LosTTAngeles', 'SanTTJose', 'SanTTFrancisco', 'Denver', 'KansasTTCity', 'StTTLouis', 'Dallas', 'Albuquerque', 'Phoenix', 'SanTTDiego'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Portland', [PathReq(Protocols.OSPF, "Portland", ['Seattle', 'Portland'], False), PathReq(Protocols.OSPF, "Portland", ['Seattle', 'Chicago', 'StTTLouis', 'KansasTTCity', 'Denver', 'SanTTFrancisco', 'SanTTRafael', 'SantaTTRosa', 'Portland'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Sacramento', [PathReq(Protocols.OSPF, "Sacramento", ['SantaTTRosa', 'Sacramento'], False), PathReq(Protocols.OSPF, "Sacramento", ['SantaTTRosa', 'SanTTRafael', 'SanTTFrancisco', 'Concord', 'Stockton', 'Sacramento'], False)], False),
]

edges_cost_order_4_2 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 1),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

reqs_simple_8 = [
    PathReq(Protocols.OSPF, "Atlanta", ['Denver', 'KansasTTCity', 'StTTLouis', 'Dallas', 'Atlanta'], False),
    PathReq(Protocols.OSPF, "Chicago", ['Denver', 'KansasTTCity', 'StTTLouis', 'Chicago'], False),
    PathReq(Protocols.OSPF, "Seattle", ['Denver', 'KansasTTCity', 'StTTLouis', 'Chicago', 'Seattle'], False),
    PathReq(Protocols.OSPF, "Portland", ['Denver', 'SanTTFrancisco', 'SanTTRafael', 'SantaTTRosa', 'Portland'], False),
    PathReq(Protocols.OSPF, "Boston", ['Denver', 'KansasTTCity', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland', 'Boston'], False),
    PathReq(Protocols.OSPF, "Cleveland", ['Denver', 'KansasTTCity', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland'], False),
    PathReq(Protocols.OSPF, "Sacramento", ['Denver', 'SanTTFrancisco', 'SanTTRafael', 'SantaTTRosa', 'Sacramento'], False),
    PathReq(Protocols.OSPF, "SanTTAntonio", ['Denver', 'KansasTTCity', 'StTTLouis', 'Dallas', 'Austin', 'SanTTAntonio'], False),
]

edges_cost_simple_8 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 2),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 2),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

####################

reqs_ecmp_8_2 = [
    ECMPPathsReq(Protocols.OSPF, 'Philadelphia', [PathReq(Protocols.OSPF, "Philadelphia", ['SanTTAntonio', 'Houston', 'Dallas', 'Atlanta', 'Raleigh', 'Washington,TTDC', 'Baltimore', 'Philadelphia'], False), PathReq(Protocols.OSPF, "Philadelphia", ['SanTTAntonio', 'Austin', 'Dallas', 'Atlanta', 'Raleigh', 'Washington,TTDC', 'Baltimore', 'Philadelphia'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'KansasTTCity', [PathReq(Protocols.OSPF, "KansasTTCity", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'KansasTTCity'], False), PathReq(Protocols.OSPF, "KansasTTCity", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'KansasTTCity'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Boston', [PathReq(Protocols.OSPF, "Boston", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland', 'Boston'], False), PathReq(Protocols.OSPF, "Boston", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland', 'Boston'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Anaheim', [PathReq(Protocols.OSPF, "Anaheim", ['SanTTAntonio', 'Austin', 'Dallas', 'Albuquerque', 'Phoenix', 'SanTTDiego', 'Anaheim'], False), PathReq(Protocols.OSPF, "Anaheim", ['SanTTAntonio', 'Houston', 'Dallas', 'Albuquerque', 'Phoenix', 'SanTTDiego', 'Anaheim'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Pittsburgh', [PathReq(Protocols.OSPF, "Pittsburgh", ['SanTTAntonio', 'Houston', 'Dallas', 'Atlanta', 'Raleigh', 'Washington,TTDC', 'Pittsburgh'], False), PathReq(Protocols.OSPF, "Pittsburgh", ['SanTTAntonio', 'Austin', 'Dallas', 'Atlanta', 'Raleigh', 'Washington,TTDC', 'Pittsburgh'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'SantaTTRosa', [PathReq(Protocols.OSPF, "SantaTTRosa", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'Chicago', 'Seattle', 'Portland', 'SantaTTRosa'], False), PathReq(Protocols.OSPF, "SantaTTRosa", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'Chicago', 'Seattle', 'Portland', 'SantaTTRosa'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Raleigh', [PathReq(Protocols.OSPF, "Raleigh", ['SanTTAntonio', 'Houston', 'Dallas', 'Atlanta', 'Raleigh'], False), PathReq(Protocols.OSPF, "Raleigh", ['SanTTAntonio', 'Austin', 'Dallas', 'Atlanta', 'Raleigh'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Baltimore', [PathReq(Protocols.OSPF, "Baltimore", ['SanTTAntonio', 'Austin', 'Dallas', 'Atlanta', 'Raleigh', 'Washington,TTDC', 'Baltimore'], False), PathReq(Protocols.OSPF, "Baltimore", ['SanTTAntonio', 'Houston', 'Dallas', 'Atlanta', 'Raleigh', 'Washington,TTDC', 'Baltimore'], False)], False),
]

edges_cost_ecmp_8_2 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 1),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

reqs_kconnected_8_2 = [
    KConnectedPathsReq(Protocols.OSPF, 'Philadelphia', [PathReq(Protocols.OSPF, "Philadelphia", ['SanTTAntonio', 'Houston', 'Dallas', 'Atlanta', 'Raleigh', 'Washington,TTDC', 'Baltimore', 'Philadelphia'], False), PathReq(Protocols.OSPF, "Philadelphia", ['SanTTAntonio', 'Austin', 'Dallas', 'Atlanta', 'Raleigh', 'Washington,TTDC', 'Baltimore', 'Philadelphia'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'KansasTTCity', [PathReq(Protocols.OSPF, "KansasTTCity", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'KansasTTCity'], False), PathReq(Protocols.OSPF, "KansasTTCity", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'KansasTTCity'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Boston', [PathReq(Protocols.OSPF, "Boston", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland', 'Boston'], False), PathReq(Protocols.OSPF, "Boston", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland', 'Boston'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Anaheim', [PathReq(Protocols.OSPF, "Anaheim", ['SanTTAntonio', 'Austin', 'Dallas', 'Albuquerque', 'Phoenix', 'SanTTDiego', 'Anaheim'], False), PathReq(Protocols.OSPF, "Anaheim", ['SanTTAntonio', 'Houston', 'Dallas', 'Albuquerque', 'Phoenix', 'SanTTDiego', 'Anaheim'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Pittsburgh', [PathReq(Protocols.OSPF, "Pittsburgh", ['SanTTAntonio', 'Houston', 'Dallas', 'Atlanta', 'Raleigh', 'Washington,TTDC', 'Pittsburgh'], False), PathReq(Protocols.OSPF, "Pittsburgh", ['SanTTAntonio', 'Austin', 'Dallas', 'Atlanta', 'Raleigh', 'Washington,TTDC', 'Pittsburgh'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'SantaTTRosa', [PathReq(Protocols.OSPF, "SantaTTRosa", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'Chicago', 'Seattle', 'Portland', 'SantaTTRosa'], False), PathReq(Protocols.OSPF, "SantaTTRosa", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'Chicago', 'Seattle', 'Portland', 'SantaTTRosa'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Raleigh', [PathReq(Protocols.OSPF, "Raleigh", ['SanTTAntonio', 'Houston', 'Dallas', 'Atlanta', 'Raleigh'], False), PathReq(Protocols.OSPF, "Raleigh", ['SanTTAntonio', 'Austin', 'Dallas', 'Atlanta', 'Raleigh'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Baltimore', [PathReq(Protocols.OSPF, "Baltimore", ['SanTTAntonio', 'Austin', 'Dallas', 'Atlanta', 'Raleigh', 'Washington,TTDC', 'Baltimore'], False), PathReq(Protocols.OSPF, "Baltimore", ['SanTTAntonio', 'Houston', 'Dallas', 'Atlanta', 'Raleigh', 'Washington,TTDC', 'Baltimore'], False)], False),
]

edges_cost_kconnected_8_2 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 1),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

reqs_order_8_2 = [
    PathOrderReq(Protocols.OSPF, 'Phoenix', [PathReq(Protocols.OSPF, "Phoenix", ['SanTTDiego', 'Phoenix'], False), PathReq(Protocols.OSPF, "Phoenix", ['SanTTDiego', 'Anaheim', 'LosTTAngeles', 'SanTTJose', 'SanTTFrancisco', 'Denver', 'KansasTTCity', 'StTTLouis', 'Dallas', 'Albuquerque', 'Phoenix'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Washington,TTDC', [PathReq(Protocols.OSPF, "Washington,TTDC", ['Raleigh', 'Washington,TTDC'], False), PathReq(Protocols.OSPF, "Washington,TTDC", ['Raleigh', 'Atlanta', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland', 'Pittsburgh', 'Washington,TTDC'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Pittsburgh', [PathReq(Protocols.OSPF, "Pittsburgh", ['Washington,TTDC', 'Pittsburgh'], False), PathReq(Protocols.OSPF, "Pittsburgh", ['Washington,TTDC', 'Baltimore', 'Philadelphia', 'NewTTYork', 'Boston', 'Cleveland', 'Pittsburgh'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Baltimore', [PathReq(Protocols.OSPF, "Baltimore", ['Washington,TTDC', 'Baltimore'], False), PathReq(Protocols.OSPF, "Baltimore", ['Washington,TTDC', 'Pittsburgh', 'Cleveland', 'Boston', 'NewTTYork', 'Philadelphia', 'Baltimore'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Atlanta', [PathReq(Protocols.OSPF, "Atlanta", ['Raleigh', 'Atlanta'], False), PathReq(Protocols.OSPF, "Atlanta", ['Raleigh', 'Washington,TTDC', 'Pittsburgh', 'Cleveland', 'Detroit', 'Chicago', 'StTTLouis', 'Dallas', 'Atlanta'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Concord', [PathReq(Protocols.OSPF, "Concord", ['Stockton', 'Concord'], False), PathReq(Protocols.OSPF, "Concord", ['Stockton', 'Sacramento', 'SantaTTRosa', 'SanTTRafael', 'SanTTFrancisco', 'Concord'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Raleigh', [PathReq(Protocols.OSPF, "Raleigh", ['Washington,TTDC', 'Raleigh'], False), PathReq(Protocols.OSPF, "Raleigh", ['Washington,TTDC', 'Pittsburgh', 'Cleveland', 'Detroit', 'Chicago', 'StTTLouis', 'Dallas', 'Atlanta', 'Raleigh'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Philadelphia', [PathReq(Protocols.OSPF, "Philadelphia", ['NewTTYork', 'Philadelphia'], False), PathReq(Protocols.OSPF, "Philadelphia", ['NewTTYork', 'Boston', 'Cleveland', 'Pittsburgh', 'Washington,TTDC', 'Baltimore', 'Philadelphia'], False)], False),
]

edges_cost_order_8_2 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 1),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

reqs_simple_16 = [
    PathReq(Protocols.OSPF, "SanTTDiego", ['Phoenix', 'SanTTDiego'], False),
    PathReq(Protocols.OSPF, "Boston", ['Phoenix', 'Albuquerque', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland', 'Boston'], False),
    PathReq(Protocols.OSPF, "Anaheim", ['Phoenix', 'SanTTDiego', 'Anaheim'], False),
    PathReq(Protocols.OSPF, "Chicago", ['Phoenix', 'Albuquerque', 'Dallas', 'StTTLouis', 'Chicago'], False),
    PathReq(Protocols.OSPF, "Austin", ['Phoenix', 'Albuquerque', 'Dallas', 'Austin'], False),
    PathReq(Protocols.OSPF, "Houston", ['Phoenix', 'Albuquerque', 'Dallas', 'Houston'], False),
    PathReq(Protocols.OSPF, "Detroit", ['Phoenix', 'Albuquerque', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit'], False),
    PathReq(Protocols.OSPF, "Raleigh", ['Phoenix', 'Albuquerque', 'Dallas', 'Atlanta', 'Raleigh'], False),
    PathReq(Protocols.OSPF, "Dallas", ['Phoenix', 'Albuquerque', 'Dallas'], False),
    PathReq(Protocols.OSPF, "Albuquerque", ['Phoenix', 'Albuquerque'], False),
    PathReq(Protocols.OSPF, "SanTTAntonio", ['Phoenix', 'Albuquerque', 'Dallas', 'Austin', 'SanTTAntonio'], False),
    PathReq(Protocols.OSPF, "Seattle", ['Phoenix', 'Albuquerque', 'Dallas', 'StTTLouis', 'Chicago', 'Seattle'], False),
    PathReq(Protocols.OSPF, "Concord", ['Phoenix', 'SanTTDiego', 'Anaheim', 'LosTTAngeles', 'SanTTJose', 'SanTTFrancisco', 'Concord'], False),
    PathReq(Protocols.OSPF, "Portland", ['Phoenix', 'Albuquerque', 'Dallas', 'StTTLouis', 'Chicago', 'Seattle', 'Portland'], False),
    PathReq(Protocols.OSPF, "SantaTTRosa", ['Phoenix', 'SanTTDiego', 'Anaheim', 'LosTTAngeles', 'SanTTJose', 'SanTTFrancisco', 'SanTTRafael', 'SantaTTRosa'], False),
    PathReq(Protocols.OSPF, "Denver", ['Phoenix', 'Albuquerque', 'Dallas', 'StTTLouis', 'KansasTTCity', 'Denver'], False),
]

edges_cost_simple_16 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 2),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 2),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

####################

reqs_ecmp_16_2 = [
    ECMPPathsReq(Protocols.OSPF, 'Detroit', [PathReq(Protocols.OSPF, "Detroit", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit'], False), PathReq(Protocols.OSPF, "Detroit", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Portland', [PathReq(Protocols.OSPF, "Portland", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'Chicago', 'Seattle', 'Portland'], False), PathReq(Protocols.OSPF, "Portland", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'Chicago', 'Seattle', 'Portland'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Cleveland', [PathReq(Protocols.OSPF, "Cleveland", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland'], False), PathReq(Protocols.OSPF, "Cleveland", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Albuquerque', [PathReq(Protocols.OSPF, "Albuquerque", ['SanTTAntonio', 'Houston', 'Dallas', 'Albuquerque'], False), PathReq(Protocols.OSPF, "Albuquerque", ['SanTTAntonio', 'Austin', 'Dallas', 'Albuquerque'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Concord', [PathReq(Protocols.OSPF, "Concord", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'KansasTTCity', 'Denver', 'SanTTFrancisco', 'Concord'], False), PathReq(Protocols.OSPF, "Concord", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'KansasTTCity', 'Denver', 'SanTTFrancisco', 'Concord'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Atlanta', [PathReq(Protocols.OSPF, "Atlanta", ['SanTTAntonio', 'Austin', 'Dallas', 'Atlanta'], False), PathReq(Protocols.OSPF, "Atlanta", ['SanTTAntonio', 'Houston', 'Dallas', 'Atlanta'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Phoenix', [PathReq(Protocols.OSPF, "Phoenix", ['SanTTAntonio', 'Austin', 'Dallas', 'Albuquerque', 'Phoenix'], False), PathReq(Protocols.OSPF, "Phoenix", ['SanTTAntonio', 'Houston', 'Dallas', 'Albuquerque', 'Phoenix'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Denver', [PathReq(Protocols.OSPF, "Denver", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'KansasTTCity', 'Denver'], False), PathReq(Protocols.OSPF, "Denver", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'KansasTTCity', 'Denver'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Boston', [PathReq(Protocols.OSPF, "Boston", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland', 'Boston'], False), PathReq(Protocols.OSPF, "Boston", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland', 'Boston'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'SanTTDiego', [PathReq(Protocols.OSPF, "SanTTDiego", ['SanTTAntonio', 'Houston', 'Dallas', 'Albuquerque', 'Phoenix', 'SanTTDiego'], False), PathReq(Protocols.OSPF, "SanTTDiego", ['SanTTAntonio', 'Austin', 'Dallas', 'Albuquerque', 'Phoenix', 'SanTTDiego'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Sacramento', [PathReq(Protocols.OSPF, "Sacramento", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'Chicago', 'Seattle', 'Portland', 'SantaTTRosa', 'Sacramento'], False), PathReq(Protocols.OSPF, "Sacramento", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'Chicago', 'Seattle', 'Portland', 'SantaTTRosa', 'Sacramento'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Anaheim', [PathReq(Protocols.OSPF, "Anaheim", ['SanTTAntonio', 'Houston', 'Dallas', 'Albuquerque', 'Phoenix', 'SanTTDiego', 'Anaheim'], False), PathReq(Protocols.OSPF, "Anaheim", ['SanTTAntonio', 'Austin', 'Dallas', 'Albuquerque', 'Phoenix', 'SanTTDiego', 'Anaheim'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Chicago', [PathReq(Protocols.OSPF, "Chicago", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'Chicago'], False), PathReq(Protocols.OSPF, "Chicago", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'Chicago'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'StTTLouis', [PathReq(Protocols.OSPF, "StTTLouis", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis'], False), PathReq(Protocols.OSPF, "StTTLouis", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'Dallas', [PathReq(Protocols.OSPF, "Dallas", ['SanTTAntonio', 'Houston', 'Dallas'], False), PathReq(Protocols.OSPF, "Dallas", ['SanTTAntonio', 'Austin', 'Dallas'], False)], False),
    ECMPPathsReq(Protocols.OSPF, 'SanTTRafael', [PathReq(Protocols.OSPF, "SanTTRafael", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'KansasTTCity', 'Denver', 'SanTTFrancisco', 'SanTTRafael'], False), PathReq(Protocols.OSPF, "SanTTRafael", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'KansasTTCity', 'Denver', 'SanTTFrancisco', 'SanTTRafael'], False)], False),
]

edges_cost_ecmp_16_2 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 1),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

reqs_kconnected_16_2 = [
    KConnectedPathsReq(Protocols.OSPF, 'Detroit', [PathReq(Protocols.OSPF, "Detroit", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit'], False), PathReq(Protocols.OSPF, "Detroit", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Portland', [PathReq(Protocols.OSPF, "Portland", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'Chicago', 'Seattle', 'Portland'], False), PathReq(Protocols.OSPF, "Portland", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'Chicago', 'Seattle', 'Portland'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Cleveland', [PathReq(Protocols.OSPF, "Cleveland", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland'], False), PathReq(Protocols.OSPF, "Cleveland", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Albuquerque', [PathReq(Protocols.OSPF, "Albuquerque", ['SanTTAntonio', 'Houston', 'Dallas', 'Albuquerque'], False), PathReq(Protocols.OSPF, "Albuquerque", ['SanTTAntonio', 'Austin', 'Dallas', 'Albuquerque'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Concord', [PathReq(Protocols.OSPF, "Concord", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'KansasTTCity', 'Denver', 'SanTTFrancisco', 'Concord'], False), PathReq(Protocols.OSPF, "Concord", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'KansasTTCity', 'Denver', 'SanTTFrancisco', 'Concord'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Atlanta', [PathReq(Protocols.OSPF, "Atlanta", ['SanTTAntonio', 'Austin', 'Dallas', 'Atlanta'], False), PathReq(Protocols.OSPF, "Atlanta", ['SanTTAntonio', 'Houston', 'Dallas', 'Atlanta'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Phoenix', [PathReq(Protocols.OSPF, "Phoenix", ['SanTTAntonio', 'Austin', 'Dallas', 'Albuquerque', 'Phoenix'], False), PathReq(Protocols.OSPF, "Phoenix", ['SanTTAntonio', 'Houston', 'Dallas', 'Albuquerque', 'Phoenix'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Denver', [PathReq(Protocols.OSPF, "Denver", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'KansasTTCity', 'Denver'], False), PathReq(Protocols.OSPF, "Denver", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'KansasTTCity', 'Denver'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Boston', [PathReq(Protocols.OSPF, "Boston", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland', 'Boston'], False), PathReq(Protocols.OSPF, "Boston", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'Chicago', 'Detroit', 'Cleveland', 'Boston'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'SanTTDiego', [PathReq(Protocols.OSPF, "SanTTDiego", ['SanTTAntonio', 'Houston', 'Dallas', 'Albuquerque', 'Phoenix', 'SanTTDiego'], False), PathReq(Protocols.OSPF, "SanTTDiego", ['SanTTAntonio', 'Austin', 'Dallas', 'Albuquerque', 'Phoenix', 'SanTTDiego'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Sacramento', [PathReq(Protocols.OSPF, "Sacramento", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'Chicago', 'Seattle', 'Portland', 'SantaTTRosa', 'Sacramento'], False), PathReq(Protocols.OSPF, "Sacramento", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'Chicago', 'Seattle', 'Portland', 'SantaTTRosa', 'Sacramento'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Anaheim', [PathReq(Protocols.OSPF, "Anaheim", ['SanTTAntonio', 'Houston', 'Dallas', 'Albuquerque', 'Phoenix', 'SanTTDiego', 'Anaheim'], False), PathReq(Protocols.OSPF, "Anaheim", ['SanTTAntonio', 'Austin', 'Dallas', 'Albuquerque', 'Phoenix', 'SanTTDiego', 'Anaheim'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Chicago', [PathReq(Protocols.OSPF, "Chicago", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'Chicago'], False), PathReq(Protocols.OSPF, "Chicago", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'Chicago'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'StTTLouis', [PathReq(Protocols.OSPF, "StTTLouis", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis'], False), PathReq(Protocols.OSPF, "StTTLouis", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'Dallas', [PathReq(Protocols.OSPF, "Dallas", ['SanTTAntonio', 'Houston', 'Dallas'], False), PathReq(Protocols.OSPF, "Dallas", ['SanTTAntonio', 'Austin', 'Dallas'], False)], False),
    KConnectedPathsReq(Protocols.OSPF, 'SanTTRafael', [PathReq(Protocols.OSPF, "SanTTRafael", ['SanTTAntonio', 'Houston', 'Dallas', 'StTTLouis', 'KansasTTCity', 'Denver', 'SanTTFrancisco', 'SanTTRafael'], False), PathReq(Protocols.OSPF, "SanTTRafael", ['SanTTAntonio', 'Austin', 'Dallas', 'StTTLouis', 'KansasTTCity', 'Denver', 'SanTTFrancisco', 'SanTTRafael'], False)], False),
]

edges_cost_kconnected_16_2 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 1),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 1),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 1),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

reqs_order_16_2 = [
    PathOrderReq(Protocols.OSPF, 'Sacramento', [PathReq(Protocols.OSPF, "Sacramento", ['SantaTTRosa', 'Sacramento'], False), PathReq(Protocols.OSPF, "Sacramento", ['SantaTTRosa', 'SanTTRafael', 'SanTTFrancisco', 'Concord', 'Stockton', 'Sacramento'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Philadelphia', [PathReq(Protocols.OSPF, "Philadelphia", ['NewTTYork', 'Philadelphia'], False), PathReq(Protocols.OSPF, "Philadelphia", ['NewTTYork', 'Boston', 'Cleveland', 'Pittsburgh', 'Washington,TTDC', 'Baltimore', 'Philadelphia'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Pittsburgh', [PathReq(Protocols.OSPF, "Pittsburgh", ['Cleveland', 'Pittsburgh'], False), PathReq(Protocols.OSPF, "Pittsburgh", ['Cleveland', 'Boston', 'NewTTYork', 'Philadelphia', 'Baltimore', 'Washington,TTDC', 'Pittsburgh'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Concord', [PathReq(Protocols.OSPF, "Concord", ['SanTTFrancisco', 'Concord'], False), PathReq(Protocols.OSPF, "Concord", ['SanTTFrancisco', 'SanTTRafael', 'SantaTTRosa', 'Sacramento', 'Stockton', 'Concord'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Chicago', [PathReq(Protocols.OSPF, "Chicago", ['StTTLouis', 'Chicago'], False), PathReq(Protocols.OSPF, "Chicago", ['StTTLouis', 'Dallas', 'Atlanta', 'Raleigh', 'Washington,TTDC', 'Pittsburgh', 'Cleveland', 'Detroit', 'Chicago'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Portland', [PathReq(Protocols.OSPF, "Portland", ['Seattle', 'Portland'], False), PathReq(Protocols.OSPF, "Portland", ['Seattle', 'Chicago', 'StTTLouis', 'KansasTTCity', 'Denver', 'SanTTFrancisco', 'SanTTRafael', 'SantaTTRosa', 'Portland'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Pittsburgh', [PathReq(Protocols.OSPF, "Pittsburgh", ['Washington,TTDC', 'Pittsburgh'], False), PathReq(Protocols.OSPF, "Pittsburgh", ['Washington,TTDC', 'Baltimore', 'Philadelphia', 'NewTTYork', 'Boston', 'Cleveland', 'Pittsburgh'], False)], False),
    PathOrderReq(Protocols.OSPF, 'StTTLouis', [PathReq(Protocols.OSPF, "StTTLouis", ['Chicago', 'StTTLouis'], False), PathReq(Protocols.OSPF, "StTTLouis", ['Chicago', 'Seattle', 'Portland', 'SantaTTRosa', 'SanTTRafael', 'SanTTFrancisco', 'Denver', 'KansasTTCity', 'StTTLouis'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Boston', [PathReq(Protocols.OSPF, "Boston", ['Cleveland', 'Boston'], False), PathReq(Protocols.OSPF, "Boston", ['Cleveland', 'Pittsburgh', 'Washington,TTDC', 'Baltimore', 'Philadelphia', 'NewTTYork', 'Boston'], False)], False),
    PathOrderReq(Protocols.OSPF, 'SanTTAntonio', [PathReq(Protocols.OSPF, "SanTTAntonio", ['Austin', 'SanTTAntonio'], False), PathReq(Protocols.OSPF, "SanTTAntonio", ['Austin', 'Dallas', 'Houston', 'SanTTAntonio'], False)], False),
    PathOrderReq(Protocols.OSPF, 'SanTTRafael', [PathReq(Protocols.OSPF, "SanTTRafael", ['SanTTFrancisco', 'SanTTRafael'], False), PathReq(Protocols.OSPF, "SanTTRafael", ['SanTTFrancisco', 'Concord', 'Stockton', 'Sacramento', 'SantaTTRosa', 'SanTTRafael'], False)], False),
    PathOrderReq(Protocols.OSPF, 'SanTTFrancisco', [PathReq(Protocols.OSPF, "SanTTFrancisco", ['Denver', 'SanTTFrancisco'], False), PathReq(Protocols.OSPF, "SanTTFrancisco", ['Denver', 'KansasTTCity', 'StTTLouis', 'Dallas', 'Albuquerque', 'Phoenix', 'SanTTDiego', 'Anaheim', 'LosTTAngeles', 'SanTTJose', 'SanTTFrancisco'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Cleveland', [PathReq(Protocols.OSPF, "Cleveland", ['Pittsburgh', 'Cleveland'], False), PathReq(Protocols.OSPF, "Cleveland", ['Pittsburgh', 'Washington,TTDC', 'Baltimore', 'Philadelphia', 'NewTTYork', 'Boston', 'Cleveland'], False)], False),
    PathOrderReq(Protocols.OSPF, 'Chicago', [PathReq(Protocols.OSPF, "Chicago", ['Seattle', 'Chicago'], False), PathReq(Protocols.OSPF, "Chicago", ['Seattle', 'Portland', 'SantaTTRosa', 'SanTTRafael', 'SanTTFrancisco', 'Denver', 'KansasTTCity', 'StTTLouis', 'Chicago'], False)], False),
    PathOrderReq(Protocols.OSPF, 'SantaTTRosa', [PathReq(Protocols.OSPF, "SantaTTRosa", ['SanTTRafael', 'SantaTTRosa'], False), PathReq(Protocols.OSPF, "SantaTTRosa", ['SanTTRafael', 'SanTTFrancisco', 'Concord', 'Stockton', 'Sacramento', 'SantaTTRosa'], False)], False),
    PathOrderReq(Protocols.OSPF, 'NewTTYork', [PathReq(Protocols.OSPF, "NewTTYork", ['Philadelphia', 'NewTTYork'], False), PathReq(Protocols.OSPF, "NewTTYork", ['Philadelphia', 'Baltimore', 'Washington,TTDC', 'Pittsburgh', 'Cleveland', 'Boston', 'NewTTYork'], False)], False),
]

edges_cost_order_16_2 = [
    ("NewTTYork", "Boston", 1),
    ("NewTTYork", "Philadelphia", 1),
    ("Dallas", "Houston", 1),
    ("Dallas", "Atlanta", 1),
    ("Dallas", "Austin", 1),
    ("Dallas", "Albuquerque", 1),
    ("Dallas", "StTTLouis", 1),
    ("Philadelphia", "Baltimore", 1),
    ("Philadelphia", "NewTTYork", 1),
    ("Denver", "KansasTTCity", 1),
    ("Denver", "SanTTFrancisco", 1),
    ("SanTTJose", "LosTTAngeles", 1),
    ("SanTTJose", "SanTTFrancisco", 1),
    ("SantaTTRosa", "Sacramento", 1),
    ("SantaTTRosa", "Portland", 1),
    ("SantaTTRosa", "SanTTRafael", 1),
    ("Phoenix", "SanTTDiego", 1),
    ("Phoenix", "Albuquerque", 1),
    ("Pittsburgh", "Washington,TTDC", 1),
    ("Pittsburgh", "Cleveland", 1),
    ("Sacramento", "SantaTTRosa", 1),
    ("Sacramento", "Stockton", 1),
    ("Chicago", "Seattle", 4),
    ("Chicago", "StTTLouis", 1),
    ("Chicago", "Detroit", 1),
    ("Albuquerque", "Phoenix", 1),
    ("Albuquerque", "Dallas", 1),
    ("SanTTAntonio", "Houston", 1),
    ("SanTTAntonio", "Austin", 1),
    ("Atlanta", "Raleigh", 1),
    ("Atlanta", "Tampa", 1),
    ("Atlanta", "Dallas", 1),
    ("Tampa", "Atlanta", 1),
    ("StTTLouis", "Chicago", 1),
    ("StTTLouis", "KansasTTCity", 1),
    ("StTTLouis", "Dallas", 1),
    ("SanTTRafael", "SantaTTRosa", 1),
    ("SanTTRafael", "SanTTFrancisco", 1),
    ("Detroit", "Cleveland", 1),
    ("Detroit", "Chicago", 1),
    ("Anaheim", "SanTTDiego", 1),
    ("Anaheim", "LosTTAngeles", 1),
    ("Raleigh", "Atlanta", 1),
    ("Raleigh", "Washington,TTDC", 1),
    ("KansasTTCity", "StTTLouis", 1),
    ("KansasTTCity", "Denver", 2),
    ("Austin", "SanTTAntonio", 1),
    ("Austin", "Dallas", 1),
    ("Baltimore", "Philadelphia", 1),
    ("Baltimore", "Washington,TTDC", 1),
    ("Stockton", "Sacramento", 1),
    ("Stockton", "Concord", 1),
    ("Houston", "SanTTAntonio", 1),
    ("Houston", "Dallas", 1),
    ("SanTTDiego", "Anaheim", 1),
    ("SanTTDiego", "Phoenix", 1),
    ("LosTTAngeles", "Anaheim", 1),
    ("LosTTAngeles", "SanTTJose", 1),
    ("SanTTFrancisco", "SanTTRafael", 1),
    ("SanTTFrancisco", "Denver", 1),
    ("SanTTFrancisco", "SanTTJose", 1),
    ("SanTTFrancisco", "Concord", 1),
    ("Concord", "Stockton", 1),
    ("Concord", "SanTTFrancisco", 1),
    ("Boston", "NewTTYork", 1),
    ("Boston", "Cleveland", 1),
    ("Washington,TTDC", "Pittsburgh", 1),
    ("Washington,TTDC", "Raleigh", 1),
    ("Washington,TTDC", "Baltimore", 1),
    ("Cleveland", "Pittsburgh", 1),
    ("Cleveland", "Boston", 1),
    ("Cleveland", "Detroit", 1),
    ("Portland", "SantaTTRosa", 1),
    ("Portland", "Seattle", 1),
    ("Seattle", "Portland", 1),
    ("Seattle", "Chicago", 1),
]

####################

reqs_simple = [reqs_simple_1,reqs_simple_2,reqs_simple_4,reqs_simple_8,reqs_simple_16]

reqs_simple_vals = [edges_cost_simple_1,edges_cost_simple_2,edges_cost_simple_4,edges_cost_simple_8,edges_cost_simple_16]

####################

reqs_ecmp = [reqs_ecmp_1_2,reqs_ecmp_2_2,reqs_ecmp_4_2,reqs_ecmp_8_2,reqs_ecmp_16_2]

reqs_ecmp_vals = [edges_cost_ecmp_1_2,edges_cost_ecmp_2_2,edges_cost_ecmp_4_2,edges_cost_ecmp_8_2,edges_cost_ecmp_16_2]

####################

reqs_kconnected = [reqs_kconnected_1_2,reqs_kconnected_2_2,reqs_kconnected_4_2,reqs_kconnected_8_2,reqs_kconnected_16_2]

reqs_kconnected_vals = [edges_cost_kconnected_1_2,edges_cost_kconnected_2_2,edges_cost_kconnected_4_2,edges_cost_kconnected_8_2,edges_cost_kconnected_16_2]

####################

reqs_order = [reqs_order_1_2, reqs_order_2_2, reqs_order_4_2, reqs_order_8_2, reqs_order_16_2]

reqs_order_vals = [edges_cost_order_1_2, edges_cost_order_2_2, edges_cost_order_4_2, edges_cost_order_8_2, edges_cost_order_16_2]

####################

